language: android
android:
  components:
    - build-tools-25.0.3
    - android-25

    # Additional components
    #- extra-google-google_play_services
    #- extra-google-m2repository
    #- extra-android-m2repository
    #- addon-google_apis-google-26